import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import{Users,Truck,Wallet,LayoutDashboard,LogOut,Plus}from'lucide-react';import'./style.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;const sb=url&&key?createClient(url,key):null;
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN'}).format(Number(n||0));
function App(){const[session,setSession]=useState(null),[page,setPage]=useState('home'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState(''),[data,setData]=useState({contractors:[],vehicles:[],finances:[]});
useEffect(()=>{if(!sb)return;sb.auth.getSession().then(x=>setSession(x.data.session));const{data:{subscription}}=sb.auth.onAuthStateChange((_,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(session)load()},[session]);async function load(){let[c,v,f]=await Promise.all([sb.from('contractors').select('*').order('name'),sb.from('vehicles').select('*').order('name'),sb.from('company_finances').select('*').order('year',{ascending:false}).order('month',{ascending:false})]);setData({contractors:c.data||[],vehicles:v.data||[],finances:f.data||[]})}
async function login(e){e.preventDefault();setErr('');if(!sb){setErr('Brak konfiguracji Supabase w Netlify.');return}let r=await sb.auth.signInWithPassword({email,password});if(r.error)setErr(r.error.message)}
if(!session)return <div className="login"><div className="loginbox"><div className="brand"><b>ZET</b><span>COMMAND CENTER</span></div><h1>Panel właściciela</h1><p>Zaloguj się do bezpiecznego centrum zarządzania Zet Transport & Logistics.</p><form onSubmit={login}><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Hasło" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Zaloguj się</button></form>{err&&<div className="error">{err}</div>}<small>Dostęp wyłącznie dla właściciela</small></div></div>;
const cards=[['fin','Finanse firmy','Przychody, koszty i zysk',Wallet],['clients','Kontrahenci','Klienci i zlecenia',Users],['fleet','Flota','Pojazdy i serwis',Truck]];
return <div className="app"><aside><div className="brand"><b>ZET</b><span>COMMAND CENTER</span></div><nav><button onClick={()=>setPage('home')} className={page==='home'?'on':''}><LayoutDashboard/>Ekran główny</button>{cards.map(([id,n,,I])=><button key={id} onClick={()=>setPage(id)} className={page===id?'on':''}><I/>{n}</button>)}</nav><button className="logout" onClick={()=>sb.auth.signOut()}><LogOut/>Wyloguj</button></aside><main><header><div><div className="eyebrow">ZET TRANSPORT & LOGISTICS</div><h1>{page==='home'?'Command Center':cards.find(x=>x[0]===page)?.[1]}</h1></div><div className="status"><i/> SYSTEM ONLINE</div></header>{page==='home'&&<Home data={data} cards={cards} setPage={setPage}/>} {page==='fin'&&<Fin rows={data.finances}/>} {page==='clients'&&<Clients rows={data.contractors}/>} {page==='fleet'&&<Fleet rows={data.vehicles}/>}</main></div>}
function Home({data,cards,setPage}){let f=data.finances[0]||{},profit=Number(f.revenue||0)-Number(f.costs||0);return <><section className="hero"><div><span>PANEL OPERACYJNY</span><h2>Wszystko pod kontrolą.</h2><p>Najważniejsze dane firmy w jednym, prostym miejscu.</p></div><div className="metric"><small>OSTATNI WYNIK</small><strong>{money(profit)}</strong><span>{f.month?`${String(f.month).padStart(2,'0')}/${f.year}`:'Brak danych'}</span></div></section><div className="grid">{cards.map(([id,n,d,I])=><button className="card" onClick={()=>setPage(id)} key={id}><I/><small>MODUŁ</small><h3>{n}</h3><p>{d}</p><b>OTWÓRZ →</b></button>)}</div></>}
const Empty=({text})=><div className="empty">{text}</div>;function Fin({rows}){return <section className="panel"><div className="paneltop"><div><span>FINANSE</span><h2>Wyniki miesięczne</h2></div><button><Plus/>Dodaj miesiąc</button></div>{!rows.length?<Empty text="Brak danych finansowych. Baza jest gotowa do pierwszego wpisu."/>:<div className="table">{rows.map(r=><div className="row" key={r.id}><b>{String(r.month).padStart(2,'0')}/{r.year}</b><span>Przychód {money(r.revenue)}</span><span>Koszty {money(r.costs)}</span><strong>{money(r.revenue-r.costs)}</strong></div>)}</div>}</section>}
function Clients({rows}){return <section className="panel"><div className="paneltop"><div><span>KONTRAHENCI</span><h2>Baza klientów</h2></div><button><Plus/>Dodaj kontrahenta</button></div>{!rows.length?<Empty text="Brak kontrahentów. Możesz rozpocząć od dodania pierwszego klienta."/>:<div className="list">{rows.map(r=><div className="item" key={r.id}><div className="avatar">{r.name?.[0]}</div><div><b>{r.name}</b><span>{r.city||'—'} · {r.country||'—'}</span></div><em>{r.risk_status==='warning'?'UWAGA':'AKTYWNY'}</em></div>)}</div>}</section>}
function Fleet({rows}){return <section className="panel"><div className="paneltop"><div><span>FLOTA</span><h2>Pojazdy</h2></div><button><Plus/>Dodaj pojazd</button></div>{!rows.length?<Empty text="Brak pojazdów w bazie. Moduł jest gotowy do uzupełnienia floty."/>:<div className="fleet">{rows.map(r=><div className="vehicle" key={r.id}><Truck/><div><b>{r.name}</b><span>{r.brand} {r.model||''}</span></div><strong>{r.current_mileage?.toLocaleString('pl-PL')||'—'} km</strong></div>)}</div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);